name: HivenAPI
version: '${project.version}'
main: fr.hivenapi.Main
authors: [ Awezial ]
website: https://hivenstudio.fr/author/api
commands:
  nick:
  report:
  f:
  c:
  cosmetics:
  tp:
