name: HivenAPI
version: '1.0-SNAPSHOT'
main: fr.hivenapi.Main
authors: [ Deglam, 0xKanoe ]
website: https://hivenstudio.fr/author/api
commands:
  nick:
  report:
  f:
  c:
  cosmetics:
  tp: